identifier_name:
  min_length: # only min_length
    warning: 3 # only error
  excluded: # excluded via string array
    - id
    - URL

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - LiguillasPadelTests
  - LiguillasPadelUITests

line_length: 150

disabled_rules:
   trailing_whitespace
